### ISSUE TITLE
Problem mit Güllefass[BUG_SP]

### ISSUE THREAD

**Issue by eric4072** [Courseplay/Courseplay_FS22#1265]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Problem tritt bei Übergabe von AD auf CP auf. Das Fahrzeug befindet sich bei der Aufnahme am Vorgewende, da vorher gekalkt worden ist sieht man aber die Flecken am Feld. Jeder Fleck ist sozusagen 1 x neu nachgefüllt, wo dann das Problem auftritt.

Im Vorgewende scheint CP noch mit gelenkten Achsen ein Problem zu haben. Würde nach dem Turn im Vorgewende (bei scharfen Ecken) das Fahrzueug noch ein paar Meter nach vor fahren, müsste es nicht mit so großen Lenkbewegungen gegensteuern. Aktuell habe ich da kein Video davon, komme heute aber noch dazu.

**Actual behavior**
 Der CP-Fahrer wartet nicht bis das Schleppgestänge vollständig geöffnet ist

**Screenshots**
a Video on youtube: https://youtu.be/vxU0Fvkz_Jw 

**Courseplay version**
Version used: 7.0.1.7

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8334314/log.txt)

**Map**
NF Marsch. egal welches Feld

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on: alles installiert

**Comment by eric4072** [comment]
hallo, mit der neuesten Version hat sich das Problem erledigt, danke ;-)

CP erkennt jetzt jedoch nur mehr den fordersten Punkt vom Fahrzeug am Vorgewende. Das Fahrzeug schiebt sozusagen komplett aus dem Feld raus (Vorgewende scharf).

braucht ihr noch ein Video?

LG Eric

**Comment by ontot** [comment]
eric4072 it is absolutely not settled. the tractor does not stop while the slurry bar opens.

**Comment by Tensuko** [comment]
I will have a look at it...

**Comment by eric4072** [comment]
Hi, no here with "latest Zip yesterday" it´s fixed...

https://youtu.be/6D47TeE_jzQ 

only the problem with the wrong position detection is still here...

**Comment by ontot** [comment]
hello tensuko ... I have tried with all the slurry tanks and related bars ... it does not work with any of them. the tractor does not stop to wait the right time for them to open, but it starts much earlier

**Comment by flooo421** [comment]
helllo, same problem with the dalbo megaroll, tractor does not stop until its fully opened

**Comment by Tensuko** [comment]
What does the Giants helper do ?

**Comment by Tensuko** [comment]
> helllo, same problem with the dalbo megaroll, tractor does not stop until its fully opened

Thats an other problem and see #1287

**Comment by Tensuko** [comment]
First and last Waypoint was not a problem.
Is that a specific Tool ?
Maybe it is AD related, but when we come back from AD, CP takes over and should just drive to the last waypoint and it does its job correct (latest Main state, so next Release Version)

![fsScreen_2022_03_26_12_24_26](https://user-images.githubusercontent.com/27344744/160237236-9862db99-76d6-45e5-8d3a-22856720f576.png)

![fsScreen_2022_03_26_12_23_26](https://user-images.githubusercontent.com/27344744/160237234-6f4bbdb0-e28c-4324-97ce-3dd36507b089.png)

**Comment by ontot** [comment]
No, it is not an AD problem because AD detaches when CP attacks. The tractor, in fact, arrives perfectly at the first point of the CP. The problem is that the tractor would have to stop before starting work to wait for the boom to open. This happens both at the first starting point and after filling the slurry barrel. If you try a larger slurry barrel and its wider distribution bar you will see that as it takes longer to open the bar, the untilled earth will be much longer.

**Comment by Tensuko** [comment]
The Tractor did wait untill it was unfolded and lowered, sure can try it with a bigger one but it should work as well.

**Comment by ontot** [comment]
please do the test. maybe after the repair you made is fine, but please try it. thank you

**Comment by ontot** [comment]
Hello Tensuko. I tried with a large barrel that has a 30 meter bar. At the start it seems to go well because the tractor goes slowly enough to allow the distributor bar to open, but when the barrel empties, after going to recharge when it has to resume work the tractor does not stop and therefore leaves about 100 meters of unworked land. The tractors stop with all the other implements when they resume work, but with the slurry barrels they don't.

**Comment by flooo421** [comment]
This is the Problem ontot described: https://www.youtube.com/watch?v=TTz1IydygiU
