### ISSUE TITLE
[BUG_SP] Selection window in helper menu too far to the right / Auswahlfenster im Helfermenü zu weit rechts

### ISSUE THREAD

**Issue by Rumspringa90** [Courseplay/Courseplay_FS22#1457]
Im Helfer Menü (ESC) wird beim Job Erstellen die Auswahlfenster rechts im Bild zu weit rechts angezeigt. Siehe Screenshot. Ohne CP ist dies nicht der Fall.

**Screenshots**
![image](https://user-images.githubusercontent.com/50840355/164888929-90b4d3e7-40a9-4d34-8f16-86cf27e9ab98.png)

**Courseplay version**
Version used: 7.0.1.13

**Comment by CaptainGuppy** [comment]
I second this. However I suspect this is having to do with the latest patch from Giants (1.4.0 or 1.4.1) since the original "load and deliver", "GoTo" and so on are also showing too far to the right.

**Screenshots**
Courseplay
![1](https://user-images.githubusercontent.com/38660681/164890267-8a039d6f-bf6f-4feb-896e-c9c63e6fd013.png)

In-game AI (GoTo)
![2](https://user-images.githubusercontent.com/38660681/164890296-1d5b4699-52f7-40d9-b15a-87f183232738.png)


**Courseplay version**
7.0.1.13

**Resolution**
5120x1440

**In-game UI scale**
75%

**Comment by Rumspringa90** [comment]
Yes, but if you delete Courseplay from the mod directory, it no longer happened for me
![image](https://user-images.githubusercontent.com/50840355/164890725-a8867101-284a-4189-a6cf-b95932fb138b.png)

**Comment by CaptainGuppy** [comment]
You are right. Either disabling the mod or going back to 7.12 moves the "Create job" window to the correct position again.

Here is Courseplay version 7.12 which is having the correct window position:
![1](https://user-images.githubusercontent.com/38660681/164944047-55b563e2-7445-4937-bcfc-01741225013b.png)

**Courseplay version**
7.0.1.13

**Resolution**
5120x1440

**In-game UI scale**
75%

**Comment by schwiti6190** [comment]
Could one of you please test the fix on the branch linked above, as I don't have the necessary hardware :)

**Comment by CaptainGuppy** [comment]
@schwiti6190 Tested it and it works great! Thanks.
![2022-04-25 08_08_46-Farming Simulator 22](https://user-images.githubusercontent.com/38660681/165030280-bae00f3d-3920-43f0-811f-e0351072c323.png)

Just did a quick test, need to test more extensively before I can sign it off 🥇

**Comment by Rumspringa90** [comment]
I can confirm

**Comment by schwiti6190** [comment]
Thanks for your tests, will be fixed in the next version :)
