### ISSUE TITLE
Straw swath on/off inoperative

### ISSUE THREAD

**Issue by Keppchen** [Courseplay/Courseplay_FS22#147]
**Steps to reproduce**
Enable Straw swath completly or disable only on ~outer~ headlands

**Actual behavior**
Straw swath will stay disabled the whole time

**Expected behavior**
Straw swath should be enabled or should enable in rows

**Screenshots**
No sorry

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7777727/log.txt)

**Map**
Elmscreek

**Vehicles/ implements involved**
No

**Relevant script mods**
Auto Drive

**Comment by dansiegel1109** [comment]
They are probably asleep at this time.  There is an option which allows to fully enable swath all the time, disable swath all the time, or only disable swath on the headlands (and swath will still be enabled on the rows).  I couldn't understand from your incredibly brief bug report, which option, if any, you chose. 

Also, from experience, they will certainly require a log file, if you truly believe this to be a bug rather than a parameter settings issues.

**Comment by Keppchen** [comment]
@dansiegel1109 what are you missing? The log? Okay... i found how to enable the logging on different levels but i did not found the log file xD

And your other questions.... i don't understand what u mean. I wrote exactly what i did, what i expect and what happened. 
I wrote that I "Enabled Straw swath completly or disable only on headlands" but that the harvester never enables th straw swath. No matter which setting is chosen.

**Comment by dansiegel1109** [comment]
Sorry, I'm not a dev, just a user trying to be helpful.  The logs, FYI, are in your basegame log.txt file located in the ~/Documents/MyGames/FarmingSimulator22 directory.  Lol, I too had problems finding the logs thinking it was a specific file created by CP, but its all merged in the 1 log file (which is great because that log file will always contain the most basic info, like what mods you are using, your PC specific HW, etc).

Ok, I see now - you did in use the setting options.  The two options that would indeed have swathing SOMEWHERE.  I mistakenly understood your description as what you observed, not the settings you used.

**Comment by Tensuko** [comment]
StrawSwath setting is not implemented yet.
