### ISSUE TITLE
[BUG_SP] Convoy distance not respected

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/Courseplay_FS22#1498]
**Steps to reproduce**
Have a 2 vehicle course, i set them to be 90m away, but it not respected anymore

I have on Case vehicle it was ok, but since i changed all vehicle to Fendt, not working anomore, causing driver to block each other sometime on maneouvre

**Actual behavior**
distance of 90M nos respected

**Expected behavior**
last driver should reduce speed to be a 90m or more from the driver above

**Screenshots**
![Sans titre](https://user-images.githubusercontent.com/58886243/166136533-d8db0234-7f21-4d88-809a-f5a2e7a9402c.png)
+ video (started just as colliding sorry)
https://drive.google.com/file/d/1bAWybFGQIItR8XaUA5i4OvFgsRuaBtYs/view?usp=sharing

+ bonus, at the end of the log file, end lane mmaneouvre getting goofe, driver got to drive to the opposite side of the field to get back to the lane ????

**Courseplay version**
Version used: 7.0.1.13

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8598452/log.txt)

debug activated later during the play
happening with Fendt 1050 and fendt 1167MT

**Map**
No Man's Land

**Vehicles/ implements involved**
see log to wee if relevant mod

**Relevant script mods**
AD 2.0.0.5

**Comment by rohne83** [comment]
Interesting to know here would be the actual distance which CP estimates between both vehicles. Not sure whether this gets logged when vehicle debug is turned on, but might be worth a trial.

**Comment by Resandise** [comment]
I have notice that you have to have all the vehicle loaded with the course prior to starting any of them on the course.  Getting in one vehicle, loading the course, starting it, then going to 2nd vehicle, loading course, and starting, it ignores the convoy.  This might because you can run the saved multi courses as a single vehicle.

**Comment by Chico0008** [comment]
i'll try with new version to check if it still happen.

**Comment by Chico0008** [comment]
Just tried again with 2 seeder, still the same, when manoeuvre for corner, the 2nd driver stay too close blocking the 1st driver :/

**Comment by Tensuko** [comment]
Well, not sure how you set up the course, but I tested the following:
Create a course, save it, remove from vehicle and then load it into both vehicles.
Also:
Created a course, not save it but just copy it and paste it into other vehicle.

Both did work, but I only tested it in headland (due to not much time).
When you turn on debug, you see those blue lines pop up behind each vehicle, and also an orange number near the following car, wich shows its distance (if to close at least).

**Comment by Tensuko** [comment]
Just a recent example, how it does work:
![fsScreen_2022_05_15_18_17_38](https://user-images.githubusercontent.com/27344744/168485334-c725f76d-8512-4696-93fb-9151bed1e059.png)

The following BigM is a few Waypoints behind, it drives the first round of the island, while the other one have done it 1 or 2 rows ago, still consider the distance (orange number).

**Comment by Chico0008** [comment]
Still hapenning to me sometime
1st driver is manoeuvring a corner, 2nd drive seems to wait a little close
when 1st driver go forward, 2nd driver start to continue blocking the implement of the 1st driver.
