### ISSUE TITLE
[BUG] Windrow (Rake) No headland

### ISSUE THREAD

**Issue by bullfarmer** [Courseplay/Courseplay_FS22#155]
**Steps to reproduce**
Creating course for windrow with 2 headlands

**Actual behavior**
No headlands

**Expected behavior**
2 headlands to be executed before starting lands 

**Screenshots**

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Elmscreek

**Vehicles/ implements involved**
Vanilla rake 4 rotor kuhn 

**Relevant script mods**
None

**Comment by bullfarmer** [comment]
Seems to very when it does it and not. Tried to set a course where it drove itself to the field and it worked but not when the tractor is already on the field.

**Comment by dansiegel1109** [comment]
FYI if it matters for this issue, I haven't opened a bug report with Giants, but their AI windrowing doesn't really respect headlands that you create with manual windrowing (unlike mowing, which works pretty well in that respect).  The rows created by Giants AI windrowing seems to always go through your manually created headlands.  It didn't bother me too much because I quickly upgraded to a windrow capable mower (the BigM btw is awesome with courseplay - the only spots it misses are the square corner edges - I don't think they have yet implemented square corners yet - SO much better than Giants AI).  For me, as long as the rows are perfectly straight, manual baling wasn't affected by the Giants bug - however I can definitely see how lack of windrows prevents you from using the windrow course with the baler.  Does a course with no windrows result in the same exact course?

**Comment by pvaiko** [comment]
Description unclear. Are the headlands not generated at all? If they are generated, what does the vehicle do? Not driving the headland waypoints, skips them? etc, etc. 

Where is the log with debug channels turned on?

**Comment by Tensuko** [comment]
Closed due to inactivity.
Follow our Wiki and discripe it more clear.
