### ISSUE TITLE
Record a course

### ISSUE THREAD

**Issue by redrummed1** [Courseplay/Courseplay_FS22#1551]
Hi, I am a seasoned courseplay user and starting to get to grips with CP22.  I use an offset mower for grass in Fs19 and now Fs22, so I always record a course first time I mow so all I have to do is tell my tractor to "Drive course" when I have to mow again.

I do not see this option in CP22, I recorded a course but it was actually a custom field I recorded.

Is the ability to record a course and drive it hidden somewhere or is it going to be included at some point.

I use it a lot for fieldwork for small irregular shaped fields.

Regards
Redrummed

**Comment by Tensuko** [comment]
There will be no record course for fs22.
Use custom field and generate a course.

**Comment by IseOlen** [comment]
So sorry to read this :( 
Explained my use cases here: https://forum.giants-software.com/viewtopic.php?p=1515050#p1515050
It seems I'm not the only one missing this.

**Comment by SweeperSwift** [comment]
Nope, you are not the only one missing this. And once this goes life on git hub, many more will be missing this.

Unfortunately, since FS22, saving your custom recording as a course, has been removed! Why? The answer given is because auto-drive is meant to replace this portion of CP. But Auto Drive is not meant for fieldwork, right? Do people not know that, even in real life, being able to 'drive' your own custom recorded course on a field, is still one of the most useful features of ANY field GPS?

Being able to record your own custom course on a field is also one of the most accurate ways to get the job done exactly the way you need it to be done! The ability to do this with course play would be such a relieve because currently there is nothing in FS22 that can do exactly this. CP would be THE mod to best address this rather severe shortcoming.
