### ISSUE TITLE
[BUG_SP] Course with round corners should stay round on inner offset lane (multitool)

### ISSUE THREAD

**Issue by SilverWheelz** [Courseplay/Courseplay_FS22#1570]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Generate course w/ 2 headlands (round corners). After reaching the southwest corner on the 2nd headland, CP unexpectedly initiates a reverse maneuver for the tractor on the right lane which caused it to jackknife.

**Expected behavior**
Turn at the headland corner without having to reverse or maybe do a circle/loop turn instead.

**Screenshots**
![Screenshot (557)](https://user-images.githubusercontent.com/94125770/168948462-d5f574e1-8d3b-4d72-b0eb-8894bd45d68b.png)
![Screenshot (559)](https://user-images.githubusercontent.com/94125770/168948476-de8fb75d-fd6c-457a-90c0-f4f6a8434ba1.png)

**Courseplay version**
Version used: 7.0.1.15

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8712961/log.txt)

**Map**
Huron County Michigan 16x

 The odd thing is I ran the same setup on an oddly shaped field prior to this and had no issues. The one below is a diff. course for land rolling but I used the same course settings for seeding on that field.
![Screenshot 2022-05-18 110347](https://user-images.githubusercontent.com/94125770/168949066-b283c904-62dc-41d5-b172-e16976897e11.png)

But it struggles to turn on the southwest corner of a rectangular field? Only on that corner though.
![Screenshot 2022-05-18 110301](https://user-images.githubusercontent.com/94125770/168949033-f22a355a-8cb1-41ba-bf45-12e2b10f126b.png)

**Vehicles/ implements involved**
Which vehicle or implement? Case Magnum AFS Connect 400 by Casearias Modding and Hatzenbichler Terminator 18 by Giants.
Mod yes/no ? Yes

**Relevant script mods**
Autodrive but was not in use.

**Comment by pvaiko** [comment]
I think #1564 should have fixed this. Check when the new release 7.0.1.16 is out.

**Comment by GeorgeEarslight** [comment]
Hello, this has surfaced again.

**Steps to reproduce**
Map Gnadenthal, Versatile 4WD Pack, Bourgault pack, all Modhub
Single 23m tool. Smaller implements (~8m) don't generate this.
Rectangular field, 23m implement, 2 or 3 headlands, round corners.

**Actual behavior**
Headland corners are not round.

**Expected behavior**
Headland corners are round.

**Screenshots**
![fsScreen_2023_03_26_09_33_47](https://user-images.githubusercontent.com/30686125/227759655-2f08b6ae-83b4-4da2-8ed9-8f7450279913.png)
![fsScreen_2023_03_26_09_34_00](https://user-images.githubusercontent.com/30686125/227759656-e43ea759-0eed-40b6-bcf2-053b217f0475.png)
![fsScreen_2023_03_26_09_34_37](https://user-images.githubusercontent.com/30686125/227759657-77d99161-4b6a-4398-824f-70a735bc2899.png)

**Courseplay version**
7.2.0.5

**Log**
Does not produce course generator log

**Map*
https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=249001&title=fs2022

**Vehicles/ implements involved**
https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=240761&title=fs2022
https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=227145&title=fs2022

**Relevant script mods**
-

**Additional Information**
Happened on a custom field (35-36 )and also an automatically detected joined field (41-42-43).
Attached cpFields.xml
[cpFields.xml.txt](https://github.com/Courseplay/Courseplay_FS22/files/11070967/cpFields.xml.txt)

**Comment by pvaiko** [comment]
That's really weird. What is the turning radius of this rig? It would be good to have the full debug log. Also, custom fields are under the modSettings folder.

BTW, the course generator is under refactoring, and one of the new features is what you see here: the n outermost headlands can have rounded corners, others with turns.

**Comment by GeorgeEarslight** [comment]
Sorry for missing the log and custom field, I've not been playing FS for some time. 
Seems like the turn radius is calculated to 9m

I'm sure the new code in the generator will have generally better results, it's just that with those rigs you can't reverse.
I'd use smooth turns but leaving gaps or using 15% overlap is triggering me.
It's not a big issue anyway, I just watch out for that one turn and handle it manually.

[35-36.renameto.txt](https://github.com
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11071930/log.txt)
[log_course_Gen.txt](https://github.com/Courseplay/Courseplay_FS22/files/11071931/log_course_Gen.txt)
/Courseplay/Courseplay_FS22/files/11071929/35-36.renameto.txt)

**Comment by pvaiko** [comment]
Yeah, that's a bug, it won't round the corner if the first vertex of the field boundary is in that corner. If it's a custom field, you can redraw it, start in the middle of one of the edges, not in the corner and it should be ok.

**Comment by GeorgeEarslight** [comment]
Thanks for the tip!
