### ISSUE TITLE
[BUG_SP] Hard Crash - Hobo's Hollow - Field 20 - 3.0m with 2 headlands

### ISSUE THREAD

**Issue by Chris-Littman** [Courseplay/Courseplay_FS22#1617]
**Steps to reproduce**
Anytime I create a course on the Hobo's Hollow map. Only on field 20, and only with 3.0m wide and 2 headlands.
-Any tractor or implement.
-Changing to 3.1m wide solves the problem.
-Changing to 1 headland solves the problem.
-Changing to any other field solves the problem.

**Actual behavior**
Total hard lock of the game (giants 9.0). Need to close the unresponsive program.

**Expected behavior**
A course to be generated

**Courseplay version**
7.0.1.16

**Log**
https://gist.github.com/Chris-Littman/d3db12606c03161e935766899a7c7449
https://gist.github.com/Chris-Littman/01f1e90fe45fc15563698842e85c532b

**Map**
Hobo's Hollow x4

**Vehicles/ implements involved**
Any
Mod-no

**Relevant script mods**
All mods but CP turned off.

This hard lock occurs when trying to generate a new CP Field Work course. No course is generated and program (giants 9.0) needs to be force quit.

I'm not totally sure I have the debug channels turned on correctly. Happy to generate new logs or provide my saved game file.

Tried with 3 different tractors and several implements. It looks like when the problem occurs its string to generate multipole "blocks."
All the attempts that don't end in a hard lock only create "Block 1"

**Comment by Tensuko** [comment]
Well, that is a strange one.
@pvaiko another log, you know what the generator tries to do?
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8789548/log.txt)

**Comment by pvaiko** [comment]
First of all, there's no crash. And there's no hard lock or whatever, the course generator eventually completes the course and it looks ok. 

Looks like for some reason the generator thinks it has to split this field into 16 blocks (which should only happen with irregularly shaped fields with nooks and islands) and then is using a genetic algorithm to find out in which order these blocks should be worked on. This takes a while but eventually it completes. 

It is most likely some numerical or rounding error, possibly because the eastern edge of field 20 is not straight and the last generated track crosses that multiple time.

**Comment by Tensuko** [comment]
Normaly on those fields the generator just takes seconds.
Thats a bit unnormal.
