### ISSUE TITLE
[Question] Gamepad Support Question

### ISSUE THREAD

**Issue by sahammer** [Courseplay/Courseplay_FS22#1757]
The latest release on Modhub Says: 

> The hud is easier to use and a separate gamepad hud was added.

How does this work exactly? I've enabled gamepad support in the menu but I have no idea how to use it :) I also didn't see anything specific in the keybinds regarding this.

Thanks in advance! And awesome mod!!!

**Comment by Tensuko** [comment]
You got to turn on gamepad friendly hud.
Then you have to do stuff more on the AI Menu as not everything fits on the Hud.

**Comment by sahammer** [comment]
Ah, so you have to use the HUD that's similar to the map? You can't interact with the HUD that you're able to bring up with mouse right click?

**Comment by Tensuko** [comment]
No sry that won't be possible.
We have that smaller HUD on the right side of the screen for gamepad to quick interact with some stuff ingame and the rest is done over the map.
The game doesn't support more, or it would be way to complex and the benefit would be low, as most use mouse + keyboard.

We just wanted to try to support gamepad as much as possible and since the Giants Helper got its won menu, we tried to integrate our system there to foor gamepad support. Sry.

**Comment by sahammer** [comment]
No worries I'll try it out 👍

I assume you can start courses from there etc. It wasn't readily apparent what game pad support did so I haven't tried it yet.

I usually do have the mouse nearby but primarily drive with the controller so it'd be nice to be able to start courses with it 🙂
