### ISSUE TITLE
[Enhancement] Cotton harvester should not be blocked by own last bale.

### ISSUE THREAD

**Issue by shadow250** [Courseplay/Courseplay_FS22#1779]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
use case cotton harvester to unload a bale facing up hill
**Actual behavior**
it unloads bale and will not continue says in top right blocked by object.  the only objects present are the harvester the unloaded bale and the ground
**Expected behavior**
unload bale and continue
**Screenshots**

**Courseplay version**
7.1.0.0
**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
no mans land
**Vehicles/ implements involved**
stock case cotton harvester
Mod no 

**Relevant script mods**
Mod autodrive installed but not using actively.

**Comment by Tensuko** [comment]
> **Log**
> Please attach a log with all debug channels active.
> For help with the debug channels,
> please check out the readme at the github front page.

Where is the needed logfile?
No Screenshot?
Pls read Wiki -> https://github.com/Courseplay/Courseplay_FS22/wiki

**Comment by shadow250** [comment]
i will get what you ask later im not on the game right now

**Comment by shadow250** [comment]
these should work
[log.zip](https://github.com/Courseplay/Courseplay_FS22/files/9153916/log.zip)
[blocked.zip](https://github.com/Courseplay/Courseplay_FS22/files/9153918/blocked.zip)
.

**Comment by Tensuko** [comment]
Why .zip you can add screenshots and logs just by drag and drop.....

Anyway, seems you use skip row so the harvester got to make pockets and have to reverse.
Do you have the same problem if he doesn't have to reverse ?

**Comment by shadow250** [comment]
its the cotton harvester it shouldnt reverse. log was too big to post without zipping. pictures looked too small  its a 2 tool course the other tool was way far ahead.

**Comment by Tensuko** [comment]
Will have to figure sometihing out for this then.

**Comment by Samus1111111** [comment]
I am seeing a similar issue with square balers. I suspect the tractor is seeing the bales in the baler and becoming blocked.

Steps to reproduce
Have a tractor pulling a square baler running a route with square corners on headlands.

Actual behavior
When the tractor reaches a square corner on a headland, the baler will overshoot the turn (expected behavior) and then attempt back up to make the turn, but will become blocked when attempting to back up.

Expected behavior
The tractor should not become blocked by the baler and/or bales contained in the baler when attempting to back up and successfully make the turn.

Screenshots
![20220804170036_1](https://user-images.githubusercontent.com/2975398/182960409-7e8c7635-c311-445a-a06a-e8a87d406ac3.jpg)

Courseplay version
7.1.0.2
Log
https://gist.github.com/Samus1111111/67bb03ddf5af40eb0392eefb088134dc

Map
Haut-Beyleron

Vehicles/ implements involved
Massey Ferguson MF 8S.305 with Kuhn SB 1290 iD

Relevant script mods
Mod autodrive installed but not using actively.
