### ISSUE TITLE
[BUG_SP] CP Worker wanders and hunts when driving to work start point 

### ISSUE THREAD

**Issue by venquessa** [Courseplay/Courseplay_FS22#1787]
**Steps to reproduce**
On a larger field where work has to stop, integration with AD carries out a task and returns to the field where it hands back to CP.

1.  Generate a course in a large field.
2.  Start the CP working in the far corner with "nearest waypoint"
3. After a few waypoint, stop the worker
4. Drive outside the field, to it's edge 
5. Select "last waypoint" and hit "play"

This does not happen everytime with every implement, so there is something else going on.

**Actual behavior**
CP's path finding while driving back to the "last waypoint" seems really uncertain.  It steers left and accelerates to 10mph roughly, then slows down, steers the other way and accelerates to 10mph.  It repeats this the whole way across the field.  It looks like the algorithm is "hunting" back and forward between extremes for some reason and it won't settle on a mid point towards the target.

**Expected behavior**
The CP path finding should hunt and narrow in on the course and quite quickly settle on a stable course.  It does do this some times, IIRC.

**Courseplay version**
Version used:  7.1.0.1 - though this as also present in 7.0

**Map**
Horun County Michigan 16x

**Vehicles/ implements involved**
Last seen with ScorpionXL stone picker mod.  Also seen with default stock forage wagons.
Multiple tractors tested, Fast Trak 4220 and 8330s has this behaviour.
Mod yes/no BOTH

**Relevant script mods**
Autodrive and CP integration with same.

**Comment by venquessa** [comment]
Its not that they aren't straight, that's fine.  I was playing last night and it didn't do "the bug" once.  The courses were not straight and it had a few wobbly moments, but it still got across the field in about a minute at an average speed around 15mph.

When the "bug" I am referring to happens the path the tractor takes is like a sine wave about 8 meters amplitude and 8 meters wavelength.  The tractor accelerates to about 10mph to the left, then slows to about 3mph and turns right, accelerates to 10mph, slows to 3mph... and repeats constantly.  If it takes 1 minute at 15mph straight(ish).  It takes about 5 minutes to cover twice the distance at half the speed due to the S shape of the path.

I understand your focus is on multiplayer and when I find these tractors wandering around with "the head staggers", I can always intervene and manually drive them to the course.  

What I'd be fine with is an understanding of how I can avoid this occurring, if you know of certain conditions it's likely to occur under or any tips on avoiding it would be cool.

**Comment by venquessa** [comment]
Oh.  I did look at the pathfinding folder in the code.  Nope.  Not my type of coding :)  I don't have a mathematical background, so complex algorithm stuff, I need a dumbed down interface to that :)

**Comment by Tensuko** [comment]
We are not MP focused...

Make a Video of it with debug on to understand wahts going on and also post that logfile with debug record.

**Comment by venquessa** [comment]
It looks similar.  I think a lot of that got lost in translation.

As an update, this has not occurred in the past 3 evenings game play.  I can see the vehicles "hunt" a little side to side, but they quickly resolve onto a single bearing and get up to speed.

The change I made in my game play was to stop using the advanced "lands/racetrack" courses.  I found they were too difficult to restart with "Nearest waypoint" with so many overlapping tool up and down courses.  I do not know if this is the cause or not, just an observation. 

That issue 1622 mentions "Pure pursuit course" which I understand as determine bearing to target, turn to bearing, repeat.  It should be a straight course if there is no drift (from wind) and the target is stationary.  There was mention of the "look ahead distance" to find that way point.  I wondered, if my "Last Waypoint" is beyond that look ahead distance, such that the path finder cannot see the waypoint it might drive in a sinewave in the vague direction until it picks it up?

**Comment by kaffeemonster** [comment]
I also saw CP "zig-zagging" in this sine-wave form several times. Either whole field traverses or long row-to-row drives. It feels like some internal constant is wrong or some controller oscillating or being to slow. It is as if CP is giving too much steering input, expecting the tractor or whole machine set turning like a super tanker (or trying too strongly to correct a large delta?), and then being surprised that stuff is actually turning quite quickly, and before it can react, it's already wrong (large delta) in the other direction. So nimble tractors or tracked vehicles (eg. Fendt 1100mt) which can turn on a dime are especially susceptible to this behaviour. Coming out of a sharp turn also makes it worse.
This is, all in all, quite baffling. On the one hand CP can steer so fine/good, i had it hold complicated machine sets stable which are a nightmare to drive for a human. On the other hand you have this, CP not able to drive a simple setup straight.
And while CP "gets there" in the end most of the time, it slows the drive massively, and i saw it totally fail when CP tries to "hit" the destination, can't because it wobbles by, sharp turn, wobbles by again, sharp turn...
