### ISSUE TITLE
[Enhancement] Extra setting for width feet/meter

### ISSUE THREAD

**Issue by rumbledethumps** [Courseplay/Courseplay_FS22#1848]
Setting the main game to show tractor speed in MPH does not change the game to show tool widths in feet. Only courseplay will show tool widths in feet. This makes no sense to us North Americans. My solution is to use an external calculator when I get a tool that auto-width doesn't work on. Please take out the extra code that converts to feet - it is never needed. You'll also be fixing another bug since changing the mph/kph setting currently requires a map reload for courseplay to change over.

To clarify... when a North American changes to MPH we only want to see tractor speed changed.

**Comment by Tensuko** [comment]
Other ppl use feet, why would we take it out? Sure its needed for some.
That other bug, you only have to change it once and reload once, not a bug.

And there is no north americans only....

Can you change the speed and width ingame separated from each other?

**Comment by rumbledethumps** [comment]
The only settings are for area and velocity. Not length and volume.

The base game changes mph/kph without a reload. Requiring a reload is unexpected. Unexpected UI behavior is always a defect.

I assumed the devs were not in a MPH country (North America mostly) and wanted to let you know the experience of someone who was. No problem if you want to close this.

**Comment by Symbob** [comment]
Just to add to this, it's not just the North Americans that would like to see this change.  I'm in the UK and prefer the speed to be displayed in MPH but I would never work in feet.  So Metres would also be my preferred choice of measurement for working widths.  The shop shows working widths in Metres so I sometimes find it a bit confusing to then see the working width displayed in CP in feet.  Mind you, we're a bit weird here in the UK as we use a mix of metric and imperial measurements, but my preference would be speed in MPH, area in Acres and usually all other measurements in metric (Metres).  I think it would be good to give people the choice at least.

**Comment by HerbHall** [comment]
Since the math neccessary for conversion is so trivial, I cannot understand why Giants does not have settings that let us choose to use whatever units we want to play in. Giants needs to add settings for length and volume so we can switch them. In todays world many people use a mixture of metric and imperial. It makes sense to allow the player to choose what they want and mix and match at will.

Most machinery in the US is still sized in imkperial (inches, feet, Cubic ft, Bushels, etc). They almost always list the metric equivelants but if you look at the numbers it is clear they were not designed in metric (10 row 30" row crop = 25 ft or 7.62 meters). It might be another hundred years to switch everything to Metric (if it happens at all...). Even if they do, I might want to play historically accurate role play games so having the option is still valid.

Since Giants didn't enable the settings, I think CP should use feet and inches if I have the game settings in MPH and Acres or include a setting allowing the user to choose Imperial or Metric. Just my opinion... I only use metric in games becouse the devs are too lazy to code the computer to do the math. In real life everything in my world is shown in imperial (often with metric subtitles). I can do metric, but imperial is my native language and it kills the fun to play games that force it on me. I want to play not constantly try convert the units in my head. I instinctivly know how big 10 feet is, but 10 meters??? (Hey Google can you translate this into useful information for me...)

**Comment by Tensuko** [comment]
We seperate that so everyone can handle it as he wants.
