### ISSUE TITLE
[Question] Combine gets caught in trees or on dike every time when turning 

### ISSUE THREAD

**Issue by MeRida2104** [Courseplay/Courseplay_FS22#2037]
Hello,

I have the problem that every time CP turns (have chosen a course with beds) the combine gets caught in trees or the bike at the edge of the field. I have already enabled the setting "Use Pathfinder in turning maneuver" in the settings, but still it happens. There is so much headland available, and still every time he drives to the edge of the field where he crashes.

 I have attached log and screenshots. The combine is a mod from Modhub and the following, but should not really matter: 

https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=228187&title=fs2022

What im doing wrong? Or is it a bug? I wasn't sure, so I open just a question here.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9859626/log.txt)

![image](https://user-images.githubusercontent.com/96819380/197756129-e7cbcc8a-e741-467a-885f-76bd0174c7e8.png)
![image](https://user-images.githubusercontent.com/96819380/197756115-88057382-04e4-435f-add9-bd4eff9a0cfa.png)

**Comment by Tensuko** [comment]
Well thats becouse the pathfinder turn always geta over the 1st headland. Not sure if we can do something like number of headlands -1 @pvaiko ?

**Comment by rohne83** [comment]
I think also the back steering can play its role with such issues. I recently had look at it again, and observed that combines always get a bit off the curve especially when it's quite narrow. Don't have a recent screenshot. The attached screenshot is from older CP version but I could see similar pattern still with the latest version, just to depict that it can get off the path quite far in such curves:
![fsScreen_2022_08_14_00_26_12](https://user-images.githubusercontent.com/71030138/197803106-5278369f-e858-4d53-b269-5077b7d68b34.png)

**Comment by Tensuko** [comment]
That looks more like a turn radius not used issue, as he could not make that narrow turn and gets off the field.

**Comment by Misamangame** [comment]
If you have trees so close just make field smaller or cut them, otherwise you will always have issues with combines or any other equipment.

**Comment by MeRida2104** [comment]
Im ok with your answer, when the problems happens in the corners of  the field. But at the edge I wouldn't expect this. Especially when there are 5 headlands. Cutting trees is not the solution.

**Comment by rohne83** [comment]
> If you have trees so close just make field smaller or cut them, otherwise you will always have issues with combines or any other equipment.

1. neither would be a solution here, and 2. this is totally offtopic. Combine wouldn't have issue there if he didn't drive that far off the turn.

**Comment by Misamangame** [comment]
2m grass patch will solve this absolutely easily.  If you want to use CP just give it some space. I also don't like turning on first headland but if turning will be set for example for most inner headland it might cause problems for other machines like big seeders or plows/cultivators.  There is no best solution, always will be compromise.  By my opinion problem with combines here is just high field speed as it is by default set on 20km/h and when they are making turns they will overshoot planned route start overcorrecting themselves and end up in trees which are 2cm from edge of the field which will not happen if you will have grass patch there

**Comment by pvaiko** [comment]
> Not sure if we can do something like number of headlands -1

We can use any headland, the problem is when to use which one, it seems obvious to use the innermost or -1 for this combine, which has a relatively small turn radius and a wide working width. 

In case of a towed implement however, especially if it is not that wide, the tractor may already be well beyond the first few innermost headlands already. 

So really the choice of headland to use depends at least on front/back marker distance, turning radius and working width.

We don't absolutely have to use the headland, we could just let the pathfinder do what it can, but that may slow things down and probably result in unwanted paths in case of weird shaped fields.

**Comment by pvaiko** [comment]
> just make field smaller 

That's what we have the field margin setting for.

**Comment by rohne83** [comment]
> 2m grass patch will solve this absolutely easily.

You can only edit fields which you own. So no solution at all, and doesn't help in the discussion here.

> Or even better, would be possible to use the headland that is the next in front of us?

Guess that could do the trick, if possible

**Comment by bojanh66** [comment]
I have same issue unfortunately.
Will this be improved in next release?

[url=https://ibb.co/FW0p8xH][img]https://i.ibb.co/FW0p8xH/Farming-Simulator2022-Game-2022-11-01-15-44-11.png[/img][/url] [url=https://ibb.co/xszkCRS][img]https://i.ibb.co/xszkCRS/Farming-Simulator2022-Game-2022-11-01-15-44-14.png[/img][/url] [url=https://ibb.co/RzsYVst][img]https://i.ibb.co/RzsYVst/Farming-Simulator2022-Game-2022-11-01-15-44-32.png[/img][/url] [url=https://ibb.co/kHv2kPx][img]https://i.ibb.co/kHv2kPx/Farming-Simulator2022-Game-2022-11-01-15-44-36.png[/img][/url]

**Comment by MeRida2104** [comment]
There is a Milestone 7.1.1.6 attached to this issue. So yes, I think there are improvements coming soon.

**Comment by pvaiko** [comment]
> I have same issue unfortunately. Will this be improved in next release? 1

You did not say what version you are using (why would anyone bother...) but I guess this is after the fix as the path is on the second headland, so this is not the same issue.

This is a new problem which we did not have before, as we always stayed on the outermost headland. But those little connecting tracks between the headlands are part of the second headland and we do not filter those out....

**Comment by pvaiko** [comment]
@bojanh66 can you try with https://github.com/Courseplay/Courseplay_FS22/pull/2065 ?

**Comment by bojanh66** [comment]
I am sorry i didnt mention which version i used, it it version 7.1.1.5 but downloaded 2-3 days ago from Code - Download Zip, it was not Release version from 9 days ago.
I have recreated another same harvest course, but starting point was a few meters earlier so that the 2nd h
eadland is not in the corner of the field and now it works fine, harvester is using 2nd headland to travel to next waypoint.
Works good :)
Thanks for your hard work.

![FarmingSimulator2022Game 2022-11-02 12-36-28](https://user-images.githubusercontent.com/32069662/199480700-0d725e4d-0b24-4216-af04-5a1b228eb75e.png)
![FarmingSimulator2022Game 2022-11-02 12-36-31](https://user-images.githubusercontent.com/32069662/199480723-d929f74f-8c56-4d2b-802a-35ce53e63310.png)
![FarmingSimulator2022Game 2022-11-02 12-36-41](https://user-images.githubusercontent.com/32069662/199480751-1f49d8b4-7082-45dd-9170-aa13f817cb94.png)
![FarmingSimulator2022Game 2022-11-02 12-36-47](https://user-images.githubusercontent.com/32069662/199480768-82402858-d098-4442-94cc-8f4515245b66.png)

**Comment by pvaiko** [comment]
Ok, thanks. With pull request #2065 it should work fine even if the transition is in the corner.
