### ISSUE TITLE
[Feature] Tidy straw discharge at end of row

### ISSUE THREAD

**Issue by enderwiggin07** [Courseplay/Courseplay_FS22#2093]
**What is the problem this feature/enhancement solves?**
With "Only turning on the field" deactivated, combine harvester starts turning while straw is discharging

**Describe the solution you'd like**
Wait and make a pile or reverse briefly for a nice discharge.  With "only turning on the field" it does a really good job already. 

**Describe alternatives you've considered**
It is possible to just flash the straw chopper for a moment, this ends straw discharge for that row

**Additional context**
Turning on the field is deactivated because the map has generous grass headlands.

**Comment by enderwiggin07** [comment]
If this is considered, also when cutting in for unload with pipe in fruit, or turning for self unload, straw discharge is not tidy currently.

**Comment by Tensuko** [comment]
Seems broken also.

**Comment by coatsy35** [comment]
Be good to see this if possible.

**Comment by coatsy35** [comment]
Could we add to this that when the combine finishes the field it backs up like it does at the ends of rows to stop the huge heaps. 

Also when a corner pocket is cut out, could it not be two full header widths? so that the second pass lines up with the cutout to prevent it being missed when a baler is sent to bale the field? The same with pockets, they are half width which means they get missed when baling, but if they were full width they would be fine (also good if the combine backup up on pockets as well to prevent huge heaps)
