### ISSUE TITLE
Planter with zero capacity sprayer fails to start course with message 'Needs to be refilled'

### ISSUE THREAD

**Issue by marcus-anton** [Courseplay/Courseplay_FS22#2188]
When attempting to use CoursePlay with a planter with a zero capacity sprayer (e.g. Case IH 2150 Early Riser Planters Series), the course fails to start with a message 'Needs to be refilled'.

It seems this was fixed in commit 8e304343dfe0d094d4cc0910af3d898db6f14477, however a subsequent commit 30139faf09c1d74c4fde34ad4d2ec97fe68ae462 introduced a math.max comparing the initilized value of 1, meaning 0 is never possible and the message is hit again.

I have verified changing the initial value to 0 fixes the issue and have the change in a forked repo here: https://github.com/Courseplay/Courseplay_FS22/compare/main...marcus-anton:Courseplay_FS22:fixZeroCapacity

Happy to submit a pull request.

**Comment by Tensuko** [comment]
What is the actual problem?
You know about the option "turn off fertilizer" ?
What exact Tool is it?
Vanilla?

**Comment by marcus-anton** [comment]
The problem is the course does not start and only gives thes 'Needs to be refilled' message, even though the seed hopper is full. So its impossible for Coureplay to plant the field. I do know about the turn off fertilizer option as a work around, however this issue was previously reported and fixed (#1975) by ignoring a zero capacity sprayer on the planter.

The exact tool in my case is the Case IH 2150 Earlier Riser Planter 24 row 30" from https://farming-simulator.com/mod.php?lang=en&country=se&mod_id=201089 with no liquid fertilizer tank option selected.

**Comment by Tensuko** [comment]
![fsScreen_2022_12_22_19_26_40](https://user-images.githubusercontent.com/27344744/209202328-b133a00e-e7e6-4e9a-8fd0-7c401e95af34.png)

**Comment by Tensuko** [comment]
> I do know about the turn off fertilizer option as a work around

It is not a work arround, it is an actual option for exactly this.

**Comment by marcus-anton** [comment]
It looks like the planter in your screen shot has a liquid fertilizer tank, so its capacity would not be 0 and the issue would not occur.

I only mentioned the option being a workaround as that is what was mentioned in #1975 before a fix was implemented to ignore zero capacity. But that fix is broken on the latest and so I suggested a fix for it.

**Comment by Tensuko** [comment]
> with no liquid fertilizer tank option selected.

When there is no liquid tank configured and the tools is detected with a fertilizer option, then it is a mod Issue.
Howver you can still turn off the fertilizer in the ingame options (thats what it is for):

![Unbenannt](https://user-images.githubusercontent.com/27344744/209203066-f054a1d4-16cb-460b-8ac3-51f70c140b1f.png)

I don't want experimental changes now that isn't tested with all other options that exist, since we had no problem with this the last months. And the linked Issue I think was about the front tank. So as long we have the option to get it working, I don't want to do changes on the code.

**Comment by Tensuko** [comment]
@tn4799 want to have a look at it.
But my opinion is why not use the option we alread have....

**Comment by Tensuko** [comment]
I had the time to test some combinations with your change and it looks good so far.
However, I am always careful if someone comes arround with a fix for a specific tool, as I don't want have others the break.
I hope you can understand this....
As said, tn4799 who made the original fix will look at it too and then we check to implement it.

**Comment by marcus-anton** [comment]
No worries, I understand. This seems to be an issue if a mod makes a fertilizer tank a configuration. It seems the mod has to specify a zero capacity tank and not sure it can remove it (without making separate mods). Trying to find other mods that have this option to see if they implement it differently.

I also started testing some options and other planters and may have found an unrelated issue. It seems a standard base game planter with fertilizer tank is able to plant with Courseplay when its completely empty of seed and fertilizer. Running it manually does not plant. I removed my change to confirm its unrelated. Still looking, but thought I would mention it.

**Comment by Tensuko** [comment]
> It seems a standard base game planter with fertilizer tank is able to plant with Courseplay when its completely empty of seed and fertilizer.

You turned off the option that helper does buy fertilizer and seeds in the ingame settings?

**Comment by marcus-anton** [comment]
Oops, no I didn't...I turn that off in my games, but was running in a clean setup and didn't. Thanks!

**Comment by Tensuko** [comment]
@marcus-anton thanks for figure that out and help testing.
Will be part of the next Release.

**Comment by tn4799** [comment]
@marcus-anton Thanks for mentioning the problem. Your indeed right with your suggestion that `capacity` should have an inital value of 0. I don't know anymore why I've initialized capacity with 1 instead of 0.
With an inital value of 1 the first condition in the if is basically always true since thanks to math.max there never will be a capacity with a value of 0 selected. This is only the case if all sprayerFillUnits of the sowing machine have a capacity of 0 and also the local variable `capacity` also has an value of 0.
