### ISSUE TITLE
Bale Count and Stop

### ISSUE THREAD

**Issue by Tankieboy** [Courseplay/Courseplay_FS22#2296]
Is it possible to have a bale counting system included and set an amount of bales to press when bailing? For example on a large field you may not require 300 wrapped silage bales and only require 200. The rest of the swath could be tedderd and re-swathed to make hay bales.

**Comment by Tensuko** [comment]
We would use the Giants System, wich requiers the DLC.
But as we thought about the counter, when to reset?
When reset after start again, what happens if you have to restart it in the middle.
It would need more UI stuff again.
We decided, that the effort is too big, maybe one day, but for now I must say, sry that won't happen any time soon.

**Comment by Tankieboy** [comment]
Thanks for the update, I will carry on using the 3rd party bale counter.
