### ISSUE TITLE
Courseplay and autodrive hand over problems

### ISSUE THREAD

**Issue by Thunderloon** [Courseplay/Courseplay_FS22#2308]
have forage harvester (tractor and trailing) picking up windrow in field in "last waypoint" mode
forage harvester is full, CP driver stops and play-button goes grey

I use AD to send forage harvester to destination on AD using "road symbol" destination.

Vehicle travels to designated destination, stops for a couple seconds... play button goes green and vehicle attempts to directly return to last waypoint in field. 

My expectation is that when I have not clicked the grey play button on courseplay display it won't turn green on its own, 

This event does not occur if "first waypoint" or "nearest waypoint" are selected.    Last time this was happening I updated from AD 2007 to AD 2009 "because it was a bug in AD" which it now most certainly is not...  seems to always happen when I am not in specified vehicle but sometimes happen when I AM in specified vehicle.

Also does not happen when I am in a vehicle nearby to the destination.

It seems to mainly happen if another vehicle has an active course on a field or if the field is close to the destination.

**Comment by Tensuko** [comment]
The only way the play button turns green is when the CP Icon on the AD HUD is activated.
There is no other way AD will autostart CP.
The selected start point on the CP Hud got nothing to do with that.

**Comment by Tensuko** [comment]
Oh shit.... yes I reproduce this hmm.
Will have a look.

**Comment by Tensuko** [comment]
- HUD setting doesn't matter
- 
- Reproduction:
Get a forage wagon, fill it up with anything, start the driver on a field with e.g. nearest (CP will stop directly, because it is full).
Then use AD to drive it to the field again (no need for the empty it and stuff) it will auto restart CP.

My guess is that we have some left over flags or anything when CP gets full and expect AD to do the job and we HAVE to restart CP.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10715855/log.txt)
