### ISSUE TITLE
Problem with the combine when the pipe is open

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/Courseplay_FS22#2427]
Good morning,

I have a problem since version 7.2.0.4. The problem is the same with 7.2.0.5
If I stop the thresher manually and reactivate courseplay with the pipe open, this is what happens (see photos)
Then, impossible to fold the pipe and open the threshing machine, even if I empty it.
I removed all mods, but I still have the same problem.
If I roll back to 7.2.0.3, everything works.
Thanks in advance
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11129249/log.txt)

![image](https://user-images.githubusercontent.com/36656729/229284946-f845992d-a663-4d5b-a831-e421e7d33d3d.png)
![image](https://user-images.githubusercontent.com/36656729/229284952-26653345-2b66-48d9-978b-4fea64adf7ff.png)

**Comment by Tensuko** [comment]
That should be fixed in the next release.
Wonder how that suddenly comes up as it seemed fine in my tests.
Maybe turn on/off was too fast hmm. Try let him run again for a while or start from further away with setting last waypoint.
It should fold the combine and then unfold it again when arrives at the waypoint.
