### ISSUE TITLE
Combine Helper remains on, turn off when we don't have an automatic unloader ?

### ISSUE THREAD

**Issue by Markus33-ITA** [Courseplay/Courseplay_FS22#265]
**Steps to reproduce**
Hi. the combine does not switch off at the end of the work and the worker remains

**Actual behavior**
the worker finishes the job but is not removed and stay in the vehicle. it happened 2 more times. at first I thought it was an isolated case. but is not so

**Screenshots**
![fsScreen_2021_12_30_17_26_34](https://user-images.githubusercontent.com/96330304/147770264-18949571-eb8f-4895-962e-e6e575467a04.png)

**Courseplay version**
Version used: 7.0.0.9

**Log**
[https://pastebin.com/dx1ESqDn](https://pastebin.com/dx1ESqDn)

**Map**
US standard

**Vehicles/ implements involved**
John deere T560

**Comment by Tensuko** [comment]
This is becouse we normaly call an unloader to empty the combine, then finish the job.
Not sure how we going to improove this yet.
(Same selfunload).

**Comment by Markus33-ITA** [comment]
both the automatic unloading and the unloading at the end of the field are disabled for this I had reported it as a bug.

![fsScreen_2021_12_30_18_14_32](https://user-images.githubusercontent.com/96330304/147773750-e215fe2c-6aa0-4eea-a0d3-87940c9a1d8f.png)

**Comment by Tensuko** [comment]
It is not a bug, it is not implemented as this yet becouse our combine always wants to get unloaded and CP in the past was always on active turning it off. So just wait for us to do something about it.

**Comment by rohne83** [comment]
Don't see the problem here. When harvesting you either have an unloader/overloader or the combine unloads itself (at least for my tests it unloaded itself even at row end). Everything else doesn't make too much sense. The game engine doesn't even allow you to fold your combine before being emptied.
I still remember the discussions we had during FS 19 about when the combine CP workers shall get disengaged at work end, and in my eyes CP went for the most reasonable approach. Just turning combine off at row end might raise other issues.

**Comment by Tensuko** [comment]
We will find a solution for this, when we approach the unloading topic, pls understand that this is not very relevant for us right now.

Anyway, your reports look clearn and that is helpful, pls keep it up like that!

**Comment by Markus33-ITA** [comment]
Hi. Yes, I see. there are other problems to be solved and this can wait. what I think do not work well or that could be improved, I open the topics and try to be as detailed as possible.
I think if there were more people doing this, it would be great and would help the mod developers a lot.
