### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by FrozenStorm1029** [Courseplay/Courseplay_FS22#2654]
**What is the problem this feature/enhancement solves?**

Front loaders load bale trailer like the combine unload

**Describe the solution you'd like**

it could use some aspects of the combine unload  code and the bale load code and the bunker silo code to have the front loaders load abstract bale trailers such as the lizard haymaster

**Describe alternatives you've considered**

use a windrower course (like the combine)
and use the front loader ( as the auger)
but the front loader pick a bale up and detects the "discharge point" being the Bale trailer

**Additional context**

this would allow more realistic play and it forces you to use more equipment
im not saying remove code but make a combination between 3 parts of code to allow more realism

**Comment by Tensuko** [comment]
Loading bales with a front loader is much more difficult as you would need the exact rotation of the bales.
Also need space on the trailer as we all know they move super easy and drop.
Since some trailers start to move by itself it is nearly impossible to get this running.

So this wint happen.
If you want to use more tools then do it on your own.
