### ISSUE TITLE
[BUG_SP] Forage Harvester drives in circles, maybe don't drive to close to target, switch earlier to CP

### ISSUE THREAD

**Issue by DMunkov** [Courseplay/Courseplay_FS22#307]
**Steps to reproduce**
Start field work on field 28 | 33

**Actual behavior**
Field 28 or 33 work results in CP AI to drive in circles near the entry point

**Expected behavior**
Field 28 and 33 harvested

**Screenshots**
Video: https://youtu.be/gDPq-C-ETRw

**Courseplay version**
Version used: 7.0.0.10

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7798716/log.txt)

**Map**
Haut

**Vehicles/ implements involved**
Unmodded Krone Big X + NH 750 head

**Relevant script mods**
N/A

**Comment by Tensuko** [comment]
Started with Start Job ?

**Comment by DMunkov** [comment]
Yep, from the map view

**Comment by garo73** [comment]
The same thing happens to me on all maps but with all the MOD combines and not with the game ones!

**Comment by Tensuko** [comment]
The Problem is:
That Target Position is used for:
A) tell wich Field and where the startpoint for the course is
B) where to drive when click on start job

So when that target is not in a good position to reach the 1st waypoint, you may end up in this problem.
What you can do (for now) is, after generating the course, place the target a bit further away at a better position in front of the 1st waypoint and then start the job.

I am not sure if we can change it like, we don't have to drive very close to the target and then switch over to CP earlier.

**Comment by DMunkov** [comment]
For me it doesn't work either way - whether I'm close to the starting point or far away from it. And I don't have any modded harvester and/or heads.

Cheers.

**Comment by Tensuko** [comment]
What you show there is a Giants problem.
It tries to reach the target but drives arround it.
Use start on 1st WP with Mini HUD or start stop CP keybind (setting if 1st or nearest is in mini hud too).

Why it gets blocked, is that traffic box and it is super weird sometimes...

So the problem is not ours.
When it would drive to target on the 1st start (and not get blocked) it works like a charm.
