### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#3078]
**What is the problem this feature/enhancement solves?**
Giants New Holland 45ft Header (13.7m) detected as 13.5m by CP

**Describe the solution you'd like**
A configuration entry that sets the header to 13.7m (as that works and is correct)

**Describe alternatives you've considered**
Alter the config file myself, but it would be good if it was set correct for everyone.

**Comment by regs1980** [comment]
> Giants New Holland 41ft Header (13.7m) detected as 13.5m by CP

Varifeed 41FT is a 12 m Header.
You mean that 3162 Superflex Draper 45FT. 
This is an parentFile xml. 
It is derived from the caseIH draper3162.i3d.
In it, the iaMarker is at 13.5m and the workAreas at almost 14m
Simply change it manually or enter it yourself in VehicleConfigurations.xml.

**Comment by coatsy35** [comment]
Corrected wrong header listed above (not sure why i wrote 41ft!) 45ft is 13.7m which is what works13.5m is not using all its width. I do adjust mine, but annoying for everyone to keep adjusting it when it could be set in the config to make everyone's life easier with it. Simple for CP to add

**Comment by Tensuko** [comment]
And even more simple to use the mouse to adjust in the hud.
And how you know its 13.7? Because of the text?
If every tool is set by text, many tools would be wrong.
Keeping the lower width and have a better coverage.

**Comment by regs1980** [comment]
Because of 0.2m I don't see the effort and if Giants change something again, you have to change something again. 
You can use the plus-minus buttons in the HUD or the VehicleConfigurations.xml in the modSettings folder.
You are the first to be bothered by it so far.

There are also a few other headers that have completely different iaMarker values than the working width in the game. 
The HD50F is supposed to have 15.2m, but has 15.6m.
The Varifeed 41FT is supposed to have 12m, but has 12.5m.
etc.

**Comment by Tensuko** [comment]
Additional info just that you know what 0.2m are, use I think F4? To view the grid, one square is 2m x 2m.
