### ISSUE TITLE
No path found to chopper[BUG_SP]

### ISSUE THREAD

**Issue by Martin-L45** [Courseplay/Courseplay_FS22#3127]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.
First off. It is awesome to see this feature back in courseplay. 

The unloader can not find a path to the chopper. It needs to be very close before it can find a path

**Expected behavior**
To be able to find a path from the edge of the field

**Screenshots**
![Farming Simulator 22 Screenshot 2024 03 10 - 16 17 33 06](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/80be6941-18d4-4f4e-b468-721a1cc28aaa)

![Farming Simulator 22 Screenshot 2024 03 10 - 16 18 51 59](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/6282d040-155e-4c7a-a60e-7edbef05f3a5)

**Courseplay version**
Version used: 
Latest version

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/14550721/log.txt)

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by coatsy35** [comment]
I have just had similar, i will attach my logs below 

Didn't have debug on for this picture, but i turned it on afterwards, the unloader gets quite close behind the forager on corners, so when creating the pocket for turning the corner it crashed into the unloader and stopped the operation. 

![fsScreen_2024_03_10_15_35_18](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/ea1d79bc-3a74-4c30-921a-84db6b0fc9c0)

Then I struggled to get the two to connect again, until i drove the unloader right up next to the forager, as the unloader just kept saying no path. Here is the log for interest if it's any use.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/14550797/log.txt)

On the return to the field the the unloader could not find a path to the forager

![fsScreen_2024_03_10_16_00_39](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/e2c5fa1c-a24d-4c1a-b529-b147f885e34f)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/14550842/log.txt)

**Comment by Tensuko** [comment]
@coatsy35 That looks more like a mod Issue.
As always, not all mods are made like Vanilla Tools and we can only and will only work on that base.

What we can try it to somehow add the offsets to the autoaim.

@Martin-L45
Thats strange.... I will test that Chopper later, but the one I used (I think JD and Claas) worked without any problem with unload on field and also found its way over a longer distance to the chopper.

**Comment by Martin-L45** [comment]
@Tensuko I unzip my mods because i tweak and edit most of the ones i use to make them look and work the way i want them to.
But i try to always do Courseplay tests with ingame equipment. 

I will try again with only Courseplay in the modfolder.

**Comment by Martin-L45** [comment]
@Tensuko I have just made a new test with only Courseplay and Autodrive in the modfolder.
This time there was no issues. So i must have a mod conflict of some kind. I will try to track it down. But i think we can close the issue...

**Comment by Crinouche** [comment]
Good morning,

First of all, thank you for this Courseplay option. I was looking forward to this.

I did a lot of testing. and I notice some problems:
1) I too have the same problem as Martin-L45 and coatsy35. Some tractors can't find the way to reach the forage harvester (photo 1) In particular, in my case, the McCormick X8 (photo 3) I tried with different trailers, but nothing helps, the McCormick can't find the way (and it's not a mod). On the other hand, if I approach the McCormick close to the forage harvester and in the right direction (photo 2), it will find the forage harvester and it will work normally. Likewise, if I take another tractor with the same trailer, it works.
2) Is it possible that the tractor is positioned further forward. Next to the forage harvester? (photo 4) Sometimes the forage harvester has difficulty finding the trailer.
3) The turns of the tractor and trailer are tight at the end of the field, and sometimes the forage harvester does not detect the trailer (photo 5&6). I have tried with different forage harvesters, including the Krone BigX 1180, even with different pipe lengths, but sometimes it does not detect. Would it be possible for the tractor to make wider turns, in order to get directly next to the forage harvester?
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/14561508/log.txt)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/8021c4c2-18d8-45bc-8c76-c8c7af65adad)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/5b1b14f6-bd3c-4146-8ab5-580bf70e07cc)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/5169cfd5-d66a-416f-8749-a52a0fd7849c)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/4a020578-a424-4da9-af34-df98016c69fd)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/819f4485-2787-4f5f-861c-b73180621a14)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/91c78ef1-ef2b-4a04-ae73-b46fd9c066cd)

**Comment by Tensuko** [comment]
> i tweak and edit most of the ones i use to make them look and work the way i want them to

That is not always how they will work correctly....

**Comment by Tensuko** [comment]
Should be fixed in the next Release.
Maybe also help with that mod chopper, but as always, mods that don't follow Giants standards, can't rly support them.

**Comment by coatsy35** [comment]
@Tensuko dropped the code for the fix into my copy and it has fixed the issue with the mod chopper. Appears to be working well now 👌Can't believe how smooth your chopper code works 😎

**Comment by Crinouche** [comment]
Thanks for your answers
sorry, my english is not very good.

"_Thats the turn radius of tractor and trailer, should be written in the log._"
 I don't understand that, but I thinks it's not important

_"Suggestion (what I always do) use the Racetrack pattern for center strategy, works best for chopper. That pattern was designed for chopper in FS19."_
Can you tell me what is"the Racetrack pattern for center strategy?"

**Comment by coatsy35** [comment]
> Thanks for your answers sorry, my english is not very good.
> 
> "_Thats the turn radius of tractor and trailer, should be written in the log._" I don't understand that, but I thinks it's not important
> 
> _"Suggestion (what I always do) use the Racetrack pattern for center strategy, works best for chopper. That pattern was designed for chopper in FS19."_ Can you tell me what is"the Racetrack pattern for center strategy?"

some observations from your pictures. Working in "lands" is a better method of cutting a field if you want to go up and down, which is what I do and now works thanks to the fix thats incoming. this same setting can be changed to racetrack which is what Tensuko mentioned.

![Screenshot 2024-03-11 213700](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/96a34237-b95d-4c72-9499-2b9becd82885)

**Comment by Crinouche** [comment]
Could you give me a screenshot of a field, to illustrate what "racetrack" is? Because in French, I can't find the right translation

**Comment by Tensuko** [comment]
If you go on "up/down" and then click 2 times the button to the right, so the 3rd option is racetrack, before that is spiral.
