### ISSUE TITLE
[Feature] Hawe SUW 5000 Augerwagon Support

### ISSUE THREAD

**Issue by regs1980** [Courseplay/Courseplay_FS22#3198]
The Hawe SUW 5000 is already partially supported.
It can be loaded and also drives to a waiting vehicle with trailer for unloading.
As he has the hedge unloader and the pipe unloader, CP cannot decide which one to use.
The unloader drives to the stationary vehicle, activates the pipe, and then cannot overload the Hawe SUW 5000. 
The rear ejector of this snail car is of no interest to CP and can also be deactivated so that only the pipe ejector works. 

A small example of what it looks like on the field in real life.
https://www.youtube.com/watch?v=TwUXohMmhHc

**Comment by Tensuko** [comment]
@schwiti6190 
1,5 parts are missing for this one.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/096f8dea-c3e2-4cdb-a813-f8a679568d23)

0,5 part.... it must be set to use the pipe to unload....
1 important part, in order to make it unload, you got to press "i" to start unloading (but tool doesn't need to be turned on).
