### ISSUE TITLE
[Question] Course generation takes 10 times longer on new version

### ISSUE THREAD

**Issue by Martin-L45** [Courseplay/Courseplay_FS22#3457]
I am playing on a custom 4xmap with very large fields 100+ Hectares. I have never had issues generating a course on this map.
When using the new version it takes about 10 times longer to generate a course approx. 47minutes.
Is this a bug or do you believe it is on my end?
the Version 7420 i am using is the main after issue #3399

[logV7420.txt](https://github.com/user-attachments/files/17102652/logV7420.txt)
[logV7421.txt](https://github.com/user-attachments/files/17102653/logV7421.txt)

**Comment by Tensuko** [comment]
I have not noticed any difference, but I don't have those XXXXL fields.

**Comment by Tensuko** [comment]
But this one is not on the 100+ HA field I hope...
"working width: 1.0"

**Comment by pvaiko** [comment]
@Martin-L45 don't think it is on your end. Does the field have islands? Can you try with island bypass off?

**Comment by pvaiko** [comment]
> But this one is not on the 100+ HA field I hope... "working width: 1.0"

That's our island detection.

**Comment by Martin-L45** [comment]
I´ll try with island bypass off

**Comment by Martin-L45** [comment]
Without islands it only took about a minute
[log.txt](https://github.com/user-attachments/files/17102928/log.txt)

**Comment by pvaiko** [comment]
Thanks, confirmed bug.

**Comment by cwattyeso** [comment]
May I also add that with the current version of Courseplay loading into a Save Game on a 4X or larger map takes an incredibly long amount of time now, and going into the game menu and performing a save takes an incredibly long amount of time also. Never happened on Version v7.4.1.3 at all. However since 7.4.2.0 this issue has appeared.

**Comment by Tensuko** [comment]
Thats too less informations.

**Comment by pvaiko** [comment]
> an incredibly long amount of time 
Can you quantify?

I changed the serialization of courses to XML to a more readable and straightforward format with no obscure encoding, it is certainly chattier than the old format but was hoping it is still fast enough. 

Do you have a savegame I can look at? With a publicly available map?

**Comment by cwattyeso** [comment]
I can provide my save file definitely and also a link to the map I'm playing on. I wondered if the increased loading and saving time was caused by using two root crop harvesters (Only 4 meters working width) and a huge field, because in the map view there is a hell of a lot of courseplay stuff going on in that field. I'm not saying I set the course up optimally for the field, and didn't know the above about deactivating the Island Bypass bit, so maybe the course being loaded upon game start and each time the game is saved is a bit excessive.

**Comment by pvaiko** [comment]
Island bypass should only matter when you generate. 

Would be great if we could compare apples to apples, if you now have two 40 km long courses you did not have with 7.4.1.3, that may skew the results a bit...

**Comment by Martin-L45** [comment]
I tried the last commit. (I hope that is ok)

Now i does not detect the islands. 

[log.txt](https://github.com/user-attachments/files/17134957/log.txt)
![Farming Simulator 22 Screenshot 2024 09 25 - 18 42 51 24](https://github.com/user-attachments/assets/15920801-bda2-4e8d-9c84-3c2c30c099cb)

**Comment by pvaiko** [comment]
> I tried the last commit. (I hope that is ok)

Sure, thanks for testing, I did not have a chance yet to test on a map with a real island. Will look into it.

**Comment by cwattyeso** [comment]
> Island bypass should only matter when you generate.
> 
> Would be great if we could compare apples to apples, if you now have two 40 km long courses you did not have with 7.4.1.3, that may skew the results a bit...

I don't have any saved courses on game since updating Courseplay to current version. I deleted all old 7.4.1.3 as wondered if too much old info was causing the game to take so long to load and save. I now have literally just the one course created and saved on the map and it's still causing the game to load and save slow. If I disable Courseplay in the mod menu before loading, the loading and saving goes back to normal pretty much.

The map I'm playing on is Flatout Farm and can be downloaded from Author's Google Drive Link: https://drive.google.com/file/d/1OaMceN3iVUpeNYSfsorqND8uR-aEH6e9/view

My save game:
[savegame13.zip](https://github.com/user-attachments/files/17135351/savegame13.zip)

**Comment by Martin-L45** [comment]
I tried your last commit. 

Perfect course generation. Only about 2 minutes. Detects the island with no issues.
There is a couple of warnings in the log. But i think that is field related.

[log.txt](https://github.com/user-attachments/files/17153222/log.txt)

![Farming Simulator 22 Screenshot 2024 09 26 - 19 27 18 86](https://github.com/user-attachments/assets/4c0a1fa9-2a32-4d3c-a973-7ad396374c0b)

**Comment by pvaiko** [comment]
Thanks, warnings are normal, removed some forgotten debug messages too.

**Comment by Martin-L45** [comment]
With multiple tools the result can get a bit weird. But by adjusting number of headlands and starting position i can get a good course. 
![Farming Simulator 22 Screenshot 2024 09 26 - 20 15 33 22](https://github.com/user-attachments/assets/927bb31c-71a8-4ac4-a784-7b3474bd98e0)
![Farming Simulator 22 Screenshot 2024 09 26 - 20 22 21 99](https://github.com/user-attachments/assets/31467504-536b-4359-9ed1-2aa01b44b6bf)
![Farming Simulator 22 Screenshot 2024 09 26 - 20 26 52 07](https://github.com/user-attachments/assets/7d7a35c3-fb3a-4b44-bf08-31ebf85bf486)

**Comment by Tensuko** [comment]
There is always a limit :)

**Comment by Martin-L45** [comment]
very true. 
And that is no problem when i can generate a course in 2minutes. Compared to 47minutes.😊
