### ISSUE TITLE
[Feature]Smoother headland generation

### ISSUE THREAD

**Issue by gsShooter** [Courseplay/Courseplay_FS22#3510]
**What is the problem this feature/enhancement solves?**
If the field border is not 100% smooth, the course generated for the headland is very uneven.

**Describe the solution you'd like**
I would like to have some sort of smoothing of the generated headland course.

**Additional context**
I have used Courseplay version 7.4.2.3 and here I made a short video of the generated headland and it's behavior in the game.

**Video link**
https://youtu.be/yRfQ2xNVDt0

**Comment by Tensuko** [comment]
Example screenshot?

**Comment by Tensuko** [comment]
Hmm the problem here is that it is already "smoothed" out by increasing the scan steps of the field border.
BUT when we set it back to the old value, you have again a higher chanze that the scan step jumps over to the next field and you will have the problem again that 2 fields are marked together. Thats what we wanted to solve with this.

**Comment by gsShooter** [comment]
Is it possible to smooth it out some more after scanning the field border?
