### ISSUE TITLE
[BUG] Work width in Feet not Metres, also auto width not working

### ISSUE THREAD

**Issue by Stu1986** [Courseplay/Courseplay_FS22#380]
Working width in Feet not Metres, also is it possible to have an auto width button

![Pic1](https://user-images.githubusercontent.com/95050337/148421521-e14ffeac-6437-443d-abed-c4e1b026dd0f.jpg)

![Pic2](https://user-images.githubusercontent.com/95050337/148421530-81254f75-54e5-48af-bab5-b430d51271bc.jpg)

**Comment by Tensuko** [comment]
Can't reproduce, no logfile, no template.

Auto workwidth is already asked for.

**Comment by PDXJedi** [comment]
Auto work width is functioning, can manually confirm the ft>M conversion. But I came here looking for a way to change this setting to meters as well. as of (CP 7.0.1.2) I'm also getting working width listed in feet instead of meters. Speed settings in the CP settings auto change from mph to kph based on adjustments to game settings: but there seems to be no tie in to that, nor am I seeing a way to change that displayed implement info (from Ft to M) 
![Screenshot (27)](https://user-images.githubusercontent.com/61521195/155812531-36a721bf-5378-49ae-b337-94847111baaa.png)
.

GIST log 
(https://gist.github.com/PDXJedi/0dcad8f8d9a554fef987dabc3fbad6a1)
