### ISSUE TITLE
[BUG_SP] Skipping sharp corners and no sharp corners at the bottom left of the fields.

### ISSUE THREAD

**Issue by JustDen1234** [Courseplay/Courseplay_FS22#440]
Created a course with 4 headlands, sharp corners, up/down, 5m.

The combine does the first headlands as it should.
On the other headlands, the combine does not make sharp corners.
It does not stop, and reverse, but just keeps driving forward making a wide turn.

In the below screenshot, the red lines show the way the combine takes these corners, instead of stopping, going back etc.
![2022-01-08 17_38_24-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/148653165-9ec04c5e-0e90-44cd-9244-22293d9825e6.jpg)

Version used: v7.0.0.16 
Log file: https://gist.github.com/JustDen1234/63a637dfcdf08755c2cde400215fc05a
Map: No Mans Land
Combine: Rostselmash Nova 330 (start combine on map)

Installed script mods:  
- AutoDrive
- AIVE 

Settings for creating the course:
![2022-01-08 18_07_16-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/148653183-1468807d-4293-448d-a236-338255e39187.jpg)

Generated course looks like this:
![2022-01-08 18_06_43-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/148653201-1df6e9bc-dcb3-466a-bd40-468e385ec874.jpg)

# Another issue with this generated course:
I shose sharp corners, my field has 90 degrees corners, but only in this corner CP generated smooth corners (in the other corners it generated sharp corners).
![2022-01-08 17_45_04-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/148653174-f5adaf9a-ee69-4db1-8fcd-32b144472cd4.jpg)

**Comment by Tensuko** [comment]
The Skip should be fixed with the next release.
The other thing I am not sure, maybe we have something in there that improoves it.

**Comment by rohne83** [comment]
For the second issue: cannot see it in the picture, but looks like the outer border got worked appropriately. But this makes me think about the inner headland lanes: right now, if the outer lane's curve is not generated as a sharp but a smooth one (because it's not necessary for the outer lane as in that picture), also the inner lanes will be generated just as smooth ones, often resulting in pieces being left over, as is the case for normal 'smooth' corners. Is it possible for sharp headland corner setting to decrease the radius of such curves from headland lane to headland lane (as already done for the 'round' setting), and as soon as this radius would be too narrow for the vehicle switching this one into a normal sharp corner just for the respective lanes. The same is done in RL in such situations.

![fsScreen_2022_01_08_20_57_34b](https://user-images.githubusercontent.com/71030138/148678077-3e7c2728-9776-49ea-a2ae-56e939e60cd8.png)

**Comment by Tensuko** [comment]
@rohne83 
I have more feedback about the bottom left corner always gets generated round.
Should try some fields but it seems like a bug.

**Comment by Tensuko** [comment]
@JustDen1234 as your issue is partly fixed, but the round corners not, I would like to merge your Issue to a round corners only Issue ( #502 ).
Yea that one is in german, but it will be mantioned in the change log and if I don't forget it I will also tag your Issue there.
