### ISSUE TITLE
[BUG_SP] Course Generation creates un-necessary overlap

### ISSUE THREAD

**Issue by clubpetey** [Courseplay/Courseplay_FS22#445]
**Steps to reproduce**
Generate course on Grass field shown in image (Erlengrat map) with 10m working width, 6 Headland rows.

**Actual behavior**
Generated course creates overlap between headland rows and center areas.  It also overlaps between headland rows when the headlands overlap themselves. See screenshot.  

**Expected behavior**
CourseGen should realize it's already covered these areas once and not run over them again. In the case of the northern loop, the area was covered after the 3rd headland, further trips should bypass the peninsula. OR don't allow more than 2-3 headlands, but some fields like the one shown would be better processed with a headland spiral than the usual up/down. 

In the FS19 version of CP, You could process an entire field as headlands (setting headlands parameter to say 30) which would create a nice spiral.

**Screenshots**
![image](https://user-images.githubusercontent.com/2221486/148663806-8c91d5ea-7fff-4f52-8af8-df9bc3f1ce09.png)

**Courseplay version**
Version used: 7.0.0.16

**Log**
n/a

**Map**
n/a

**Vehicles/ implements involved**
I used a Big M 450 in the screenshot

**Relevant script mods**
none

**Comment by rohne83** [comment]
Don't think it's too easy to implement to have the course generator decide if a headland lane can be skipped in any random part of such a field. With just adding more headland you have the tradeoff of more and more parts of the field which remain completely unworked.
Don't know if that can be implemented, but what could be interesting for such kind of fields would be a contour option for normal up/down fieldrows (instead of heaving these worked as perfectly straight lines).

**Comment by pvaiko** [comment]
The course generator is probably the only area where we changed nothing since 19, so I'm pretty sure you'd get the exact same result in 19 for this field.

I'm sure there is a way to implement what you expect, It would be a very interesting challenge, unfortunately I don't have the time for it now. As always, pull requests are welcome!
