### ISSUE TITLE
[Question] Mini HUD selecting by arrow keys

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#489]
Since some days i saw this, but i can´t reproduce exactly:

if i load the savegame, i´m able to switch the starting points in the mini HUD by pressing the left or right arrow key.
after some time it won´t work anymore till the next restart of game or new loading a savegame

Question: is it basicly programmed to switch by the arrow keys or is it a side-effect?
If yes, what can cause the mailfunction of it?

**Comment by Tensuko** [comment]
Not sure why it stops working.
Can you check if you have a LUA Error in your log when it stops working ?

**Comment by KCHARRO** [comment]
> Not sure why it stops working. Can you check if you have a LUA Error in your log when it stops working ?

This happens to me when I use autodrive, when starting it with ctrl + alt + up, it disables the arrow keys, not only in CP but also in the entire game interface ...

from that same vehicle already working AD, I get off and get on it and then the direction keys start working again, this happened to me in FS19, I don't think it's CP problems, I'll try it with CP alone without AD...

**Comment by Tensuko** [comment]
Interesting, thanks for the feedback.

**Comment by RealNeo80** [comment]
i can confirm about ctrl+alt+up in AD, but im veeery shure that i never used this

**Comment by schwiti6190** [comment]
Is this problem only happing when ad is active in the savegame as mentioned above ?

**Comment by RealNeo80** [comment]
need to be tested, because i have AD all time on in my game and don´t play without. Maybe someone is playing without and can test it

**Comment by KCHARRO** [comment]
This is not a Courseplay issue, although there was a time the day before yesterday, in one of the updates (can't remember which one) that worked fine, yesterday it kept blocking the arrow keys again.

There is something, but it is difficult to determine what causes it, but I am sure it is AD, although CP influences over AD a lot, mainly in the "Combine Download" mode since yesterday, he has taken to driving on the crops, sometimes he gets in front of the combine, sometimes it is lost in the active unloading, and when CP makes pockets, the AD unloader does not go back (and sometimes just goes straight ahead) and does not give the combine room, and when resuming the march it causes collisions with the header.

My conclusion is that, because AD hasn't been updated for more than a week "2.0.0.3", and it does weird things for a couple of days only since CP_7.0.0.19. It is the influence of CP on AD. (it is strange to me)

Tonight when I get home, I'll update from the main branch, and try it out and see what it does.

**Comment by KCHARRO** [comment]
Last night, I tried again with the updated main, and it does the same thing (only if you press ctl+alt+up).

It's not CP, don't break your head with this anymore. AD is the cause.

**Comment by Tensuko** [comment]
@KCHARRO Is this reported on AD GitHub ?
If yes, can you post the link here ?
So we have a link between those Issues.

**Comment by Tensuko** [comment]
Not sure where it does come from, but could not confirm as a problem from CP. Since we keep change things, this might not be actual a problem anymore.

**Comment by RealNeo80** [comment]
@Tensuko still a problem in 7.0.0.21 but i will check in further versions. I´m pretty shure its not coming -only- from AD. I´ll check if there is an issue open there, if not i create one, maybe they have an idea.
