### ISSUE TITLE
Grapes - Olives

### ISSUE THREAD

**Issue by HC1Gunner** [Courseplay/Courseplay_FS22#49]
I tried to get CP to work on a small field of grapes, but no matter what settings I used, always comes back with "target unreachable". I realize you're starting from scratch, but...
To me it looks like it no longer does all its own math, and CP is using part of the built-in Helper, it's still buggy itself and doesn't always work.
My point is, instead of this CP using its own math, it appears to rely on what Giants has created for the helper AI, we both know Giants can't do half their $hit correctly. So if the base game has an issue, you've now just built that issue right into CP.

![FarmingSimulator2022Game_2021_12_24_16_41_20_528](https://user-images.githubusercontent.com/45585444/147373139-4883eea4-b2b0-4b22-a03c-4048b4c835a1.jpg)

**Comment by Tensuko** [comment]
Is Giants able to use the Harvester for this ?
If not we can check if can create a driver for this, but it won't be easy.

**Comment by HC1Gunner** [comment]
It takes a lot longer for grapes and olives to mature than regular crops, I
have yet to harvest any of them. I will do a test map, and fast-fwd their
growth, and get back to you on the harvester.

**Comment by Beedog743** [comment]
No. Grapes and olives you can't use a worker for most of the tools. The only took that sort of works is the sub soiler. It can go down the row but that is it

**Comment by fudoido** [comment]
it doesnt work for olives and grapes for the simple reason that those are placeable items, not a regular crop. helper AI or courseplay  will plan a path through the entirety of the field just planning the tool width, not detecting where the crop rows are. 
The only way i see it working is to manually record the paths through the placeable lines of the olives and grapes and make it use that path as fieldwork mode, be it for fertilizing, spraying and even harvesting, trying to make CP detect the placeable rows will be a big task i believe.
If it helps, thefarmsimguy at youtube posted a video some days ago to edit a XML file in order to allow to reduce the spacing between rows, so that you can mulch and fertilize on a single passage in that row, instead of going 2 times on the same row. with that in mind, maybe a course can be generated if you set the same row distance in the CP menu, but without headlands since those crops do not have space for headland work, they start straight from the edge of the fields.
can a course be recorded and then make it work as fieldwork mode with a mulcher or sprayer?

**Comment by HC1Gunner** [comment]
I went the other route, some created the implements to a wider path, only
needing one pass on each of the new wider rows, and then I increased the
speed 7 to 10 mph.
There are too many places I need to be, visiting family during the
holidays, but when I get a chance, I will try to record a path and see if
that works.
I knew they were seen as objects, but I figured CP would just see a field,
and not care what was on it. I created my course, and set the width of the
implement wider, to be on center with each row. Somehow when Giants added
the changes in the patch, creating a snap-line for grapes and olives, their
snap-line is not true north-south or east and west. If you use GPS, center
yourself at one end, by the time you reach the other end, you will be off
center. Not sure how they managed it, but someone did not check their work.

**Comment by Elite82pt** [comment]
So I really like grapes and Olives but having no Helper makes it a lot more grinding when you have a bigger field of grapes to cover the cost of the harvester. If you add back the manual record of the course and a button or even shortcut to define the start and end the row that would be more than enough to start out

**Comment by Tensuko** [comment]
Manual Record takes a lot more then just a button.
I may have another Idea but that is not very high on the priority list, sry.

**Comment by aviator64** [comment]
I have figured out a workaround that will let you use CP with your grapes. Basically you create the course and then plant your grapes to match it.

Choose a rectangular field, get in a tractor with any implement connected, and go into CP course generation for the field. **Select a working width of 3 meters** - remember you are concerned with the spacing of the grape vines, NOT the implement. I recommend setting skip rows to 1 as they are so narrow. Generate the course and save it.

Now, turn on "all waypoints visible" in the tractor's CP settings so you can see the entire course.

Go into the build menu and select grapes. You can still see the CP course. Place your first grape pole about 10m in from the edge of the field, halfway between the CP course lines. I like to start on a row in the middle of the field. Drag to the other end of the row, about 10m from the edge, and place the end pole, again halfway between the CP course lines. Check to make sure your row of grapes is perfectly parallel with the CP course - if not you can demolish it and place it again.

Planting 10m in from the edge of the rows is to give your tractor plenty of room to turn and get lined up with each row.

Planting the rest of the rows is easy since subsequent rows of grapes will snap to the previous one.

If your first or last CP rows are not full width, just don't plant a row of grapes there.

This will of course make just one pass with the tractor, down the center of each row. I don't see that making two passes per row, so as to get every scrap of grass, makes any real difference to the yield.

Your sprayer covers two rows in each pass, so if you set it to skip 1 row as suggested, you can stop it halfway through.

When it comes time to harvest or prune, use the same course with a horizontal offset (might take some trial and error to get the offset right) so the machine lines up with the vines.

**Comment by Elite82pt** [comment]
> I have figured out a workaround that will let you use CP with your grapes. Basically you create the course and then plant your grapes to match it.
> 
> Choose a rectangular field, get in a tractor with any implement connected, and go into CP course generation for the field. **Select a working width of 3 meters** - remember you are concerned with the spacing of the grape vines, NOT the implement. I recommend setting skip rows to 1 as they are so narrow. Generate the course and save it.
> 
> Now, turn on "all waypoints visible" in the tractor's CP settings so you can see the entire course.
> 
> Go into the build menu and select grapes. You can still see the CP course. Place your first grape pole about 10m in from the edge of the field, halfway between the CP course lines. I like to start on a row in the middle of the field. Drag to the other end of the row, about 10m from the edge, and place the end pole, again halfway between the CP course lines. Check to make sure your row of grapes is perfectly parallel with the CP course - if not you can demolish it and place it again.
> 
> Planting 10m in from the edge of the rows is to give your tractor plenty of room to turn and get lined up with each row.
> 
> Planting the rest of the rows is easy since subsequent rows of grapes will snap to the previous one.
> 
> If your first or last CP rows are not full width, just don't plant a row of grapes there.
> 
> This will of course make just one pass with the tractor, down the center of each row. I don't see that making two passes per row, so as to get every scrap of grass, makes any real difference to the yield.
> 
> Your sprayer covers two rows in each pass, so if you set it to skip 1 row as suggested, you can stop it halfway through.
> 
> When it comes time to harvest or prune, use the same course with a horizontal offset (might take some trial and error to get the offset right) so the machine lines up with the vines.

Hey there!
I tested and it works actually really well!!! Thanks for the idea!

**Comment by aviator64** [comment]
Glad it worked for you! Yes, as of today the harvester and pruner will still not hire a helper. Hopefully either Giants or CP will solve that issue soon.

**Comment by Elite82pt** [comment]
> @Elite82pt How does that work with harvester? I'm able to load a course into it, but the 'Play' button is missing then, and it cant be activated over the keyboard.
> 
> Is this still somthing, that just needs time or is this a bug?
> 
> Also cutting down the grapes with tractor and the cutting tool cant be automated for me, same issue, no ability to start the course. If i plug the cultivator, then CP can be started.

It doesn't work with the harvester as of right now...
let's hope in the future we can...

**Comment by aviator64** [comment]
> > @Elite82pt How does that work with harvester? I'm able to load a course into it, but the 'Play' button is missing then, and it cant be activated over the keyboard.
> > Is this still somthing, that just needs time or is this a bug?
> > Also cutting down the grapes with tractor and the cutting tool cant be automated for me, same issue, no ability to start the course. If i plug the cultivator, then CP can be started.
> 
> It doesn't work with the harvester as of right now... let's hope in the future we can...

I have found that Vehicle Control Addon (VCA) can help with harvesting and pruning. You'll still have to make the turns at the end of the rows but you don't have to manually steer all the way down each row. If you set up VCA with 3m wide lanes it will snap to the next row when you make your turn.

**Comment by HC1Gunner** [comment]
I have not messed with CP for awhile, but I'm going to start using it again
on my next map. I just use guidance steering (GPS), but the only problem
with that is, I believe it was the 1.2 patch where Giants changed the way
grapes and olive rows were planted (construction), where they now had a
snap-line. The problem is someone at Giants did not check their work, most
everything in this game involves math, and I'm not sure how they could mess
this up, but they did. The problem is that if you put rows in North - South
(0 - 180 degrees), or East - West (90 - 270 degrees) the snapline is not
true north/south or east/west, it is off by a degree or two. Of course the
longer your row the further you will be off by the time you reach the other
end. If you use GPS your center line will slowly start to take you into the
vines row, so you have to keep nudging the GPS over as you travel. I
alerted Giants to the issue with their snapline of grapes and olives not
running in true directions, but apparently they could care less, and have
never replied.
