### ISSUE TITLE
[BUG_SP] open/close vehicle settings display

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#501]
**Steps to reproduce**
open/close vehicle settings display mit der Taste (habe es auf strg+S gelegt) -> öffnen funktioniert, schliessen nicht (nur mit ESC Taste)

**Expected behavior**
das settings display sollte mit derselben taste geschlossen werden können

**Courseplay version**
7.0.0.17

lg
andreas

**Comment by RealNeo80** [comment]
i don´t know why ESC shouldn´t work, 
but i think should be not the biggest thing to implement that you can also close over the keybinding

@Tensuko but if we are here talking over improvements of the mini HUD, 

1) we had so so many questions about why it wont start from the last point, so i think due to that the HUD is bind to the vehicle why not set the HUD automatically to start from last point, wen a job was stopped?

2) how much effort is it to activate the camera and vehicle steering, when the MiniHud is open? its annoying if i need to close when i like to look around, or steer the vehicle

**Comment by Tensuko** [comment]
@RealNeo80 
Mit ESC geht es ja, mit dem Keybind geht es nicht zum schließen.
Liegt daran das es das GUI von Giants ist was wir da verwenden.

Zu Punkt1: Das ist eine gute Idee, ich frage mal ob sich das so umsetzen lässt. (Wenn gestoppt bei WP >=1 setze Einstellung auf nahesten WP).

Zu Punkt2: Das geht nicht, weil es ein komplettes overlay ist, wie auch die Menüs von z.B. GPS oder VCA.

**Comment by andreasthu** [comment]
Oh yeah, you are right.
 there are so many things to work on.
(For my own i miss the ingame course editor so much)
It is ok for me to close it with esc.
But in the ingame help stands "open/close"
So i thought it should work, but doesnt.
And sometime it ist easy when i got a small look at it i press the key, then a 2nd time to close, before i search the esc key.
Lg
Andress

**Comment by andreasthu** [comment]
Danke, funktioniert super
lg
andreas
