### ISSUE TITLE
[Feature] Set Default CP config for HUD

### ISSUE THREAD

**Issue by Rosencrafter** [Courseplay/Courseplay_FS22#719]
**What is the problem this feature/enhancement solves?**
Everytime i have a loaner, the standard CP Config is "Open Hud un rightklick" when rightklicking is also used for AD

**Describe the solution you'd like**
Set the default to deactivated... opening the HUD with shortcut is sufficient.

**Comment by Roby1164** [comment]
?? AD uses the middle mouse button, by default, not the right one. But it's always customizable at will, I don't see why it should be turned off by default

**Comment by Tensuko** [comment]
As Roby said, no reason to change default.

**Comment by Rosencrafter** [comment]
Ok.
But you are aware that you use the right mouse button to move AD Waypoints arround?
Its pretty anoying if you need to adjust a AD course on a new vehicle, when your mous is vanishing every two klicks...

**Comment by Roby1164** [comment]
> As Roby said, no reason to change default.

I have to correct myself. Actually there is a problem of conflict, in the phase of modification of the paths of the AD, it is necessary to use the right mouse button, to move the points, otherwise it changes the setting of the CP button, it prevents to use it. So it would be better to be able to define another key, perhaps the middle key, for the function in CP.
