### ISSUE TITLE
[Feature] Field edge detection using crop type and/or field owner

### ISSUE THREAD

**Issue by vlil** [Courseplay/Courseplay_FS22#837]
When fields are very close together, the course generator doesn't alway detect the edge of your current field.

Recording the border manually works as a workaround, but it might be possible to use crop type and/or owner to improve the accuracy of automatic edge detection.

If crop type or field owner changes, the course generator could take a step back and move forward in smaller increments until the field edge is found.

Thanks for a great mod!

**Comment by pvaiko** [comment]
A check of the field ID is actually already implemented but currently disabled because it does not work with merged fields, these keep their different IDs even after the merge. Owner also would not help if both fields happen to belong to you, and crop also not reliable as it can be anything at a given spot or nothing...

On the long term we could implement a setting to enable using the field ID in the field scanner.
