### ISSUE TITLE
Mowing grass on Erlengrat Map with CP 7.0.0.3

### ISSUE THREAD

**Issue by BarnyHarz** [Courseplay/Courseplay_FS22#85]
Hello guys,

first of all thank you for the release version of CP for LS22.
I have an issue with course generator for mowing grass on Erlengrat map.
If i try to generate a course on a piece of land where the meadow has no connection to another piece of land it works properly. I will attach a picture of the generated course.
When iI try to generate a course on a meadow, which is separated by 2 or more parts of land, the course generator is not working. It can´t generate a course, even if you have purchased all land parts of the meadow. Second screenshot will show this, red line is marking the meadow.
 I will also attach the log.txt for debugging.

Maybe it will be possible to generate courses for those meadows in the future.
![CP_Screen1](https://user-images.githubusercontent.com/63304301/147386922-a852c19e-7063-41af-853a-5f49b8b4e923.JPG)
![CP_Screen2](https://user-images.githubusercontent.com/63304301/147387010-1351fe47-fc8e-45a6-a1bc-84e644a74cd6.JPG)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7775942/log.txt)

**Comment by pvaiko** [comment]
Sorry, but that's a bit too complicated for our course generator. It shows that it had to split this field into 32 blocks (with a total of 165 rows to work) and then figure out in which order to work on those 32 blocks (using a genetic algorithm). 

This is due to the many islands and nooks this field has. You may experiment with selecting the longest edge for the start direction, or changing the 30 here (but it'll take a long-long time to finish): https://github.com/Courseplay/Courseplay_FS22/blob/b63f376688d6758f2c7df218c528416418326686/scripts/courseGenerator/center.lua#L286

**Comment by BarnyHarz** [comment]
Thank you for your fast answer. I appreciate it. Have a nice holiday.
